
notifications:
  email:
    on_success: never
    on_failure: always

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      language: generic
      env:

before_install:
  - cmake .

install:
  - make
